on:
  push:
    branches:
      - master

jobs:
  clojars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jlesquembre/clojars-publish-action@0.3
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
          GIT_REF: false
